### ISSUE TITLE
Captions are not displayed with modified URLs

### ISSUE THREAD

**Issue by Khartir** [webgilde/image-source-control#7]
We modifiy the src-URL of the images to use relative URLs instead of absolute URLs. With this, captions are no longer displayed.
The reason for this is that the caption is build by the function `get_source_by_url`. This tries to identify the image-id from the URL and the renders the caption using `render_image_source_string`.  Since the URLs are relative, `get_image_by_url` can not identify the image.
I'm curious what the reasoning behind using `get_source_by_url` is. The regex already returns the image-id. It is used to check if the image has a source: `get_post_meta($id, 'isc_image_source_own', true)`.
So why not call `render_image_source_string` directly?

**Comment by webzunft** [comment]
Thanks @Khartir for noticing this.
I must admit that I had to look very close to identify the problem here, but found the reason, finally.
The class containing image ID could be removed manually (or maybe by some plugins) from the image and is also not there if you hand code it into the content of the post. Without the ID, the image source as an overlay would not work.
I am sure there is a partial fix to only use `get_source_by_url` if needed, but the current code works for all situations and I don't see an urgent reason to make it more complex.
Please, feel free to argue on that and make a pull request for a change.

**Comment by Khartir** [comment]
I'll try and get a pull-request ready some time next week, which would first try and read the id from the class (which is what wordpress does to create the srcset and sizes attribute) and as a fallback uses `get_source_by_url`.
