### ISSUE TITLE
Image source options not visible directly when uploaded to a post

### ISSUE THREAD

**Issue by webzunft** [webgilde/image-source-control#89]
How to reproduce:

- open a new or existing post
- add a new `image` block
- choose an existing image or upload a new one
- set the source information in the media library, e.g., like following

![Bildschirmfoto 2020-11-08 um 16 26 50](https://user-images.githubusercontent.com/2728720/98469345-4856be00-21df-11eb-8d85-3ea29d0a4589.png)

- click on "Select"
- click on the image in the post and find that the source information in the block settings are still empty

![Bildschirmfoto 2020-11-08 um 16 27 47](https://user-images.githubusercontent.com/2728720/98469364-66bcb980-21df-11eb-88a7-55ba97aadeae.png)

I would expect that the information entered already appear here already, too.

**Comment by cnhk** [comment]
@webzunft The PR is there https://github.com/webgilde/image-source-control/pull/92

This is one of the case for which I think I've said "When another user edit the source at the same time, the change will not be visible until next page load" (or something like that) the last time I worked on ISC. The other user here being the ajax calls that update the source from the media library modal frame.

The strategy I used last time is quite simple and reliable but does not cover cases like that. The previous system (the one that causes crashes) was a kind of hack that stop working at some point in time. That's why I opted for a such simple solution.

The fix for the media library here is also a kind of hack, as it relies heavily on that media library's markup to detect changes on the sources. So take your time when testing it. But at least at the time the media library changes its markup (not impossible, and some plugins might also alter it) this system will not cause JS crashes but will just stop working.

**Comment by webzunft** [comment]
Thanks.

I am not sure if it is a new bug but the Image License field is not showing a value even though one is selected even before loading the page.

![Bildschirmfoto 2020-11-16 um 16 43 17](https://user-images.githubusercontent.com/2728720/99274625-d9a2e180-282a-11eb-8c98-7a04aabac415.png)
